### ISSUE TITLE
Use cluster confidence index for cleaning

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#203]
https://github.com/dipy/dipy/blob/master/dipy/tracking/streamline.py#L327

**Comment by 36000** [comment]
This is very similar to our distance threshold, however it:
 (1) does not do a length threshold, 
 (2) does not do multiple rounds,
 (3) is defined in mm instead of SDs
 (4) uses distance between each streamline instead of to the core streamline
 The first 2 are easily fixable by slotting this into our framework, however I fail to see (3) as an advantage. (4) could be an advantage but its much slower. Unless theres some insight I am missing here, I think we can close this.
