### ISSUE TITLE
CST streamlines much less than when i use Matalab

### ISSUE THREAD

**Issue by duanliangtao** [yeatmanlab/pyAFQ#227]
when i use pyAFQ example(plot_tract_profile.py),the CST streamlines(4 lines) after segmentation much less than the AFQ in Matalab(thousands lines).I don't know what caused it，isn't Matalab better than pyAFQ，I don't know if pyAFQ is still in the optimization stage

**Comment by arokem** [comment]
Thanks for posting about this! Maybe we should emphasize this more in the
example: Because we want to be able to run it quickly (in just a few
minutes), the example only tracks very few streamlines. The recommended way
to use pyAFQ on real data is through the CLI:
https://yeatmanlab.github.io/pyAFQ/usage.html#running-the-pyafq-pipeline

**Comment by duanliangtao** [comment]
Thank you for your prompt reply.
I switched to the way you recommended,it works great when I use your data，but it has poor performance on my real data.
![image](https://user-images.githubusercontent.com/48194157/75524469-edae7500-5a48-11ea-949d-32089aa50a77.png)

It can be seen from the figure that a large number of fiber bundles are filtered out，when I traced the code, I found that it was caused by this:
![image](https://user-images.githubusercontent.com/48194157/75524723-6d3c4400-5a49-11ea-9a9a-bd869eae51b8.png)
Any idea what could be going on here?
btw can you provide your email to help me check if my data is not suitable.......
thanks a lot!!!!!
here are my result:
![image](https://user-images.githubusercontent.com/48194157/75525106-30248180-5a4a-11ea-9212-71fea467eb09.png)

**Comment by arokem** [comment]
Thanks for giving it a try and reporting back. Is the image you posted the result of the full-brain tractography (what file are you showing?)? I'd be happy to take a closer look at your data, if you are able to share. Are you able to post the data publicly (e.g., on dropbox or google drive)? I will warn you, however, that I am heading on vacation later today, so my reply here might be delayed by as much as two/three weeks.

**Comment by duanliangtao** [comment]
Thank you very much for your prompt response，The picture shows is "sub-01_sess-01_dwi_space-RASMM_model-DTI_desc-det_tractography.trk".I have shared data in googledriver(https://drive.google.com/open?id=1iCWEieR_vbs7SzA1sBKApvEkAUiXjzFE).hope you help me solve the problem after you return from vacation.By the way I wish you a relaxing holiday!!!

**Comment by arokem** [comment]
Sorry for the slowness... it's been a challenging couple of months. 

I think that once #224 is merged your issues should be resolved. I just ran this with the data you provided on that branch, and it seems to be pretty good.

 For example, here's right CST with your data on that branch:
![sub-01_sess-01_dwi_space-RASMM_model-DTI_desc-det-AFQ_CST_R_viz](https://user-images.githubusercontent.com/118582/79627729-9a26e200-80ef-11ea-9525-cf930c715081.gif)

I think that we might be able to make a release some time next week, so if you wait until then you should be able to upgrade and rerun.

**Comment by arokem** [comment]
Two more suggestions that may improve this: 

1. Having a separate white matter mask calculated through Freesurfer seems to help a lot. The software does estimate a white matter mask from the FA otherwise, but the quality of this mask is not great. 

2. If you want to have more streamlines for every tract (and potentially more coverage in cases such as CST), you might need to track with more seeds. This can be controlled by setting the `n_seeds` variable in the `[tracking]` section of the config to a number larger than 1. The main challenge there is that when you go to 2 seeds per dimension (8 per voxel) tracking becomes a much lengthier process and also requires more memory. This is something that I plan to address in an upcoming release cycle (see #241).

**Comment by duanliangtao** [comment]
I am very happy to receive your reply，thank you so much for doing so much work to help me.
I will take your suggestions and do more experiments. I am looking forward to your new version release,and experiment with my data after the new version is released.Finally express my sincere thanks!

**Comment by arokem** [comment]
We just released version 0.3 of the software, so I am going to close this now. Let me know if you run into these or other issues, or feel free to reopen this, if you think that the original issue has not been addressed.

**Comment by duanliangtao** [comment]
Sorry for taking so long to reply to you,for some reason,I did not work
during this period.I just verified,the new version solves my problem
perfectly,and perform well on other data sets.I cannot express my gratitude
to you,I will continue to pay attention to your new research!😀

Ariel Rokem <notifications@github.com> 于2020年4月22日周三 上午9:27写道：
