### ISSUE TITLE
development environment the version.py file not created unless pip install editable mode

### ISSUE THREAD

**Issue by bloomdt-uw** [yeatmanlab/pyAFQ#435]
Following instructions on https://yeatmanlab.github.io/pyAFQ/

$ git clone https://github.com/yeatmanlab/pyAFQ.git
$ pip install .
$ python
>>> import AFQ.data as afd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../pyAFQ/AFQ/__init__.py", line 1, in <module>
    from .version import version as __version__  # noqa
ModuleNotFoundError: No module named 'AFQ.version'

**Comment by 36000** [comment]
Just an update: I was able to reproduce this on my machine using a clean environment and following the example.

**Comment by 36000** [comment]
This is because the version.py is generated wherever pip is installing pyAFQ, not in the source. If you try to then run python in the source directory and import afq, it will use the pyafq in source and cause this error. You can change directories to solve this problem. For those developing with pyAFQ, it is recommended to install with `pip install -e .` instead, which would also solve this problem.
