### ISSUE TITLE
Can CLI users see the Google Analytics tracking information?

### ISSUE THREAD

**Issue by bloomdt-uw** [yeatmanlab/pyAFQ#454]

**Comment by arokem** [comment]
The whole thing is managed by this software library: https://popylar.github.io/popylar/. More concretely, popular stores a UUID in the user home directory that is then used to identify them (so that they don't get double-counted). 

In principle, the only information that is being tracked is the fact that the CLI was called (implemented [here](https://github.com/yeatmanlab/pyAFQ/blob/master/bin/pyAFQ#L71-L72)). 

In practice, I don't think that it's even working. I just looked at the Google Analytics dashboard and see 0 'visits'. I suspect that this is because the software is not doing what it's supposed to do, because I think that we should at least see the CI.

**Comment by richford** [comment]
Does mean that, assuming it's working properly, each cloudknot job would count as a unique user?

**Comment by bloomdt-uw** [comment]
If tracking is not working then maybe a separate issue should be opened. Assuming that is working then this request initiated when I first read the documentation, given the privacy considerations, evolving laws, and other services provide, I thought users might want to either see their own information and/or the aggregated project information. This might be as simple as configuring and telling them the public analytics dashboard.

**Comment by 36000** [comment]
We no longer use this.
