### ISSUE TITLE
Trouble running example scripts

### ISSUE THREAD

**Issue by jdias001** [yeatmanlab/pyAFQ#735]
I am trying to lean how to use pyAFQ in the hopes of using it to process some DKI data we have. As part of my effort, I first wanted to simply run some of the examples provided on the pyAFQ site. However, these examples do not seem to work as described.

Attached is a .pdf of my attempt to run the "RecoBundles80 using AFQ API" example. As you'll see, there is an "ImageFileError" where it "Cannot work out file type" for one of the template images.

Some insight would be greatly appreciated.

Thank you

[pyAFQ_TEST.pdf](https://github.com/yeatmanlab/pyAFQ/files/6964238/pyAFQ_TEST.pdf)

**Comment by arokem** [comment]
Thanks for reporting. Initially, I though this might be because you are running on Python 3.9, but that part works fine for me even on 3.9, so I don't think that's the issue. My current hypothesis is that the template file was somehow corrupted when it was downloaded. I wonder: if you delete the file mentioned in the error in the last cell  and then rerun, does it work?

**Comment by jdias001** [comment]
That command returned "0.8".

**Comment by jdias001** [comment]
So apparently, changing the system environment within Jupyter Labs does not change the working director. I had to reinstall Jupyter in Python 3.8. The example appears to be working now.

**Comment by arokem** [comment]
Excellent! Thanks again for reporting!
