### ISSUE TITLE
Potential workaround for the bundle UID nonsense

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#781]
Have the trk store separate data-per-streamline lists for each bundle and set it to 1 for "part of this bundle" and 0 for "not part of this bundle"

**Comment by 36000** [comment]
I am thinking of using: https://stackoverflow.com/questions/31701991/string-of-text-to-unique-integer-method
ie, 
![image](https://user-images.githubusercontent.com/9562159/145876851-ba486e58-cf3f-4f7e-aa18-e14356bced8f.png)
![image](https://user-images.githubusercontent.com/9562159/145876875-8ca3b481-5d80-4ff8-8298-20e00bacac7a.png)

**Comment by arokem** [comment]
This is a cool idea! And will save a bit of space, relative to the multiple binary variables I was suggesting.

**Comment by 36000** [comment]
For names like "CC_ForcepsMajor", my scheme won't work, because it requires too large of a number (we would have to require bundle names to be limited to ~6 characters, not including underscores). Your scheme would work but requires more space (~640MB if 80 bundles and 1M sls, instead of ~8MB). We could also keep doing the old 'uid' way, just not have it be input by the user. The only flip side to this is that we need to know the original bundle dict whenever we open the trk file, so that we know how we mapped bundle name to uid. Lots of tradeoffs

**Comment by 36000** [comment]
We should use the old system of uid's but only generate them on save, put them in the sidecar, and then look at the sidecar on load.
