### ISSUE TITLE
Corpus Callosum is assumed to be in the center of the image in CSD modeling

### ISSUE THREAD

**Issue by pierre-nedelec** [yeatmanlab/pyAFQ#952]
https://github.com/yeatmanlab/pyAFQ/blob/afcc50caa8d58da35570e0bca64091ffbf406035/AFQ/models/csd.py#L40-L41

When using the CSD model, it estimates the response function based on supposedly corpus callosum values (see [DIPY docs, strategy 1](https://dipy.org/documentation/1.2.0./examples_built/reconst_csd/#:~:text=Strategy%201%20%2D%20response%20function%20estimates%20from%20a%20local%20brain%20region)). However, by default it assumes that this will be in the center of the image (see [here](https://github.com/dipy/dipy/blob/13af40fec09fb23a3692cb0bfdcb91d08acfd766/dipy/reconst/csdeconv.py#L935-L936)). We run into cases where this is not true, and the algorithm fails to find FA values > 0.7 in the cubical region thus defined (see example below). What would be an appropriate way to mitigate that? We've been thinking of 3 potential avenues:
- use [another DIPY strategy](https://dipy.org/documentation/1.2.0./examples_built/reconst_csd/#:~:text=Strategy%202%20%2D%20data%2Ddriven%20calibration%20of%20response%20function),
- use the brain mask since it could solve a potential head not in the center of the image, but from what we've tried it doesn't help,
- extract the corpus callosum with another tool and feed its coordinates here.

Example:
![image](https://user-images.githubusercontent.com/65797646/218214932-3178637d-71b2-4f58-a5d4-5c8cc53a9e1b.png)

@suneelbanerjee

**Comment by arokem** [comment]
This could be related to preprocessing. In many pipelines, the corpus callosum ends up in the "right place", because the brain is roughly centered as part of the preprocessing. It might be a good idea to register the brain (e.g., using a rigid body registration) to the MNI template. If you do that, the corpus callosum should end up in the right place. 

If the error that gets raised is the custom CsdNanResponseError that get's raised a few lines down: https://github.com/yeatmanlab/pyAFQ/blob/afcc50caa8d58da35570e0bca64091ffbf406035/AFQ/models/csd.py#L44, we might be able to do something clever, like re-running the algorithm with a larger ROI.

**Comment by arokem** [comment]
I believe that this is resolved, so closing. But feel free to reopen for further discussion.
