### ISSUE TITLE
Default seed threshold should not be 0

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#965]
On this line: 

https://github.com/yeatmanlab/pyAFQ/blob/c2bcb5d9a4ec221ca6f09a475e7ce6b51aa9a6c7/AFQ/tractography/tractography.py#L32

We set the default of `seed_threshold` to 0, but that rarely makes sense, whether using a mask (0/1) or a scalar (usually FA). We should raise this to 0.1 (at least) or even 0.2?

**Comment by arokem** [comment]
I also found this: 

https://github.com/yeatmanlab/pyAFQ/blob/master/AFQ/tasks/tractography.py#L263

Which suggests to me that we did intend to set this to 0.2, when no value is given, but I believe that when config is automatically generated, this is over-ridden to be 0. 

@36000 : maybe you can help me here? What is the default behavior?

**Comment by arokem** [comment]
For cross-reference, I am pretty sure that the default in qsiprep is 0, and I believe this is automatically generated from the pyAFQ default: https://github.com/PennLINC/qsiprep/issues/563

**Comment by arokem** [comment]
Also, I think that the seed mask output should be a binary mask with 1s in the voxels that are used for seeding and 0s everywhere else, instead of what we currently do, which is to copy the volume that is used as a basis for thresholding (i.e., the full FA map in cases where FA is used for seeding).

**Comment by 36000** [comment]
QSIprep should be doing the same as the default pyAFQ behavior, which is the code you found here, when seed_mask is None: https://github.com/yeatmanlab/pyAFQ/blob/master/AFQ/tasks/tractography.py#L263

We can change `seed_mask=None, seed_threshold=0 ` to `seed_mask=None, seed_threshold=0.2 `, but I don't think this matters. People should pay attention to the parameters, and when they set seed_mask, also set seed_threshold.

The seed mask output being a binary mask I think makes sense. Due to interpolation, the stop mask is not usually used as a binary mask so it might be worth it to keep the stop mask as is, depending on how people use these files. Its also possible these should only be written to disk optionally.

**Comment by arokem** [comment]
This is not as big a worry as I thought earlier today. The default behavior is FA with threshold of 0.2, but that's a bit hard to glean from the config defaults. Let's leave this open until we implement the seed mask as binary (see https://github.com/yeatmanlab/pyAFQ/issues/965#issuecomment-1546246456)

**Comment by 36000** [comment]
Some changes in #1118 should make this more clear to the user: https://github.com/yeatmanlab/pyAFQ/blob/88625e200b3d69f264cd9d5de7ebb24c78814e6a/AFQ/tasks/tractography.py#L302
